### PR TITLE
Better error message with missing sudo (no parse error)

### LINKED ISSUE #278: `Sudo` over no `new_with_sudo` contract wrapper error message
In the multi-test context, to send the `Sudo` message to a contract requires creating the contract wrapper with `new_with_sudo`.
This is obvious, but when you forget to do it, the resulting error message is not clear / obvious at all:
```rust
`Result::unwrap()` on an `Err` value: "Error parsing into type alloc::string::String: Invalid type"
```

Consider improving on the error message, so a contract / test writer has a better grasp on what's failing when forgetting / not knowing about `new_with_sudo`.

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #278 

I introduced `Any` rather than `String`. `Any` is like `Empty` (parses any struct), but it has a needed `Display` implementation.
When we are happy with this, and merged, we can port over the `Display` implementation to `cosmwasm_std::Empty` for the future.

### CODE REVIEW

File: packages/multi-test/src/wasm.rs [hunk 1]
```diff
@@ -10,6 +10,18 @@ use cosmwasm_std::{
 };
 
 use crate::transactions::{RepLog, StorageTransaction};
+use std::fmt::Formatter;
+
+/// This is used as a placeholder type that can be anything
+#[derive(Serialize, Deserialize, Clone, Debug, PartialEq, JsonSchema)]
+pub struct Any {}
+
+// We couldn't use Empty as it didn't implement Display. Shall we upstream this?
```
Comment (maurolacy) [inline packages/multi-test/src/wasm.rs:19]: I think so, yes. This can be a (minor) recurrent problem.

**Review by maurolacy — APPROVED** [review]

File: packages/multi-test/src/wasm.rs [hunk 2]
```diff
@@ -48,7 +60,7 @@ type QueryClosure<T, E> = Box<dyn Fn(Deps, Env, T) -> Result<Binary, E>>;
 
 /// Wraps the exported functions from a contract and provides the normalized format
 /// Place T4 and E4 at the end, as we just want default placeholders for most contracts that don't have sudo
-pub struct ContractWrapper<T1, T2, T3, E1, E2, E3, C = Empty, T4 = String, E4 = String>
+pub struct ContractWrapper<T1, T2, T3, E1, E2, E3, C = Empty, T4 = Any, E4 = Any>
```
Comment (webmaster128) [inline packages/multi-test/src/wasm.rs:63]: Why don't you use `T4 = Empty` and `E4 = String`?

`String` is a great default error type. The only restructions those types have is `ToString`. So requiring `Display` is more than necessary.

Comment (ethanfrey) [reply packages/multi-test/src/wasm.rs:63]: Hmmm.. that might work and be a simpler solution.
Will try

Comment (ethanfrey) [reply packages/multi-test/src/wasm.rs:63]: Just approved your PR to that end
